### ISSUE TITLE
Kernel panic - not syncing: Attempted to kill init!

### ISSUE THREAD

**Issue by pedroluis5** [claudioscordino/rpi3-xenomai#2]
I'd follow your steps and on boot raspberry I got Kernel panic. I follow everything on the steps but in the copy parts I did this:

cp build/linux/arch/arm/boot/dts/bcm2837-rpi-3-b-cobalt.dtb /boot/
cp build/linux/arch/arm/boot/zImage/boot/kernel-xenomai.img
cp -r build/linux/MODULES/lib/modules/4.9.51-ipipe /lib/modules    ---is this right?

Is the last copy right?

To recover Raspberry to boot I remove the new lines from config.txt

**Comment by claudioscordino** [comment]
Yes, it is right, although I would have used "cp -a" rather than "cp -r" (which keeps symbolic links).
Also, is a space missing in "cp build/linux/arch/arm/boot/zImage/boot/kernel-xenomai.img" ?
Did you modify /boot/cmdline.txt ?
Just after menuconfig, can you try to manually overwrite the build/linux/.config with config in the main directory ?

**Comment by pedroluis5** [comment]
I've modified the cmdline.txt. On menu configure I'd create my own configuration that's can be the problem. I'll try use your config file. Thanks for your attention. I'll return as soon as I get a text.

**Comment by pedroluis5** [comment]
Hello, after rebuild with your config Xenomai boot :)
Some stuff that I have to do:
To Compile the code I've to install:
sudo apt-get install bc
sudo apt-get install libncurses5-dev

Copy config file after menuconfig
cp config linux-4.9.51/build/linux/.config

Some stuff stop working as Wifi e bluetooth, I don't know how to make wifi came back to life, I'll figure out.

What I have to put on this alias:
CROSS_COMPILE
XENOMAI_DIR
KERNEL_DIR

Thank you for your tutorial, it's great

**Comment by claudioscordino** [comment]
Do you mind testing the "next" branch ? I've simplified much  of the build process.

**Comment by pedroluis5** [comment]
Yes. I can do it for you.
